INSERT INTO public.serp_feature_index (serp_feature_raw, result_type, serp_intent) VALUES
('app download', 'App', 'Branded'),
('events', 'Events', 'Research'),
('faq / organic', 'FAQs', 'Research'),
('accordion / answers / knowledge graph / list', 'Featured Snippets', 'Answer'),
('accordion / answers / knowledge graph / paragraph', 'Featured Snippets', 'Answer'),
('accordion / answers / list', 'Featured Snippets', 'Answer'),
('accordion / answers / paragraph', 'Featured Snippets', 'Answer'),
('answers / carousel / list', 'Featured Snippets', 'Answer'),
('answers / carousel / list / related searches', 'Featured Snippets', 'Answer'),
('answers / carousel / paragraph', 'Featured Snippets', 'Answer'),
('answers / knowledge graph / paragraph', 'Featured Snippets', 'Answer'),
('answers / list', 'Featured Snippets', 'Answer'),
('answers / list / related searches', 'Featured Snippets', 'Answer'),
('answers / paragraph', 'Featured Snippets', 'Answer'),
('answers / paragraph / related searches', 'Featured Snippets', 'Answer'),
('answers / related searches / table', 'Featured Snippets', 'Answer'),
('answers / table', 'Featured Snippets', 'Answer'),
('answers / videos', 'Featured Snippets', 'Split/Fractured'),
('accordion / answers / knowledge graph / table', 'Featured Snippets', 'Answer'),
('accordion / answers / table', 'Featured Snippets', 'Answer'),
('carousel / find results on', 'Find Results On', 'Local'),
('found on the web', 'Found On The Web', 'Research'),
('explore', 'Google Explore', 'Research'),
('flights', 'Google Flights', 'Transactional'),
('hotels / placesv3', 'Google Hotels', 'Local'),
('hotels / placesv3 / ratings', 'Google Hotels', 'Local'),
('jobs', 'Google Jobs', 'Jobs'),
('shopping', 'Google Shopping', 'Transactional'),
('amp / carousel / image / organic', 'Image Carousel', 'Visual'),
('carousel / image / organic', 'Image Carousel', 'Visual'),
('carousel / ratings / search by photos', 'Image Carousel', 'Visual'),
('amp / carousel / image / ratings / organic', 'Image Carousel', 'Visual'),
('amp / image / organic', 'Images', 'Visual'),
('carousel / organic / image', 'Images', 'Visual'),
('image / organic', 'Images', 'Visual'),
('images', 'Images', 'Visual'),
('images / knowledge graph', 'Images', 'Split/Fractured'),
('indented / organic', 'Indented Results', 'Branded'),
('image / indented / organic', 'Indented Results', 'Branded'),
('image / indented / ratings / organic', 'Indented Results', 'Branded'),
('amp / image / indented / organic', 'Indented Results', 'Branded'),
('indented / ratings / organic', 'Indented Results', 'Branded'),
('amp / image / indented / ratings / organic', 'Indented Results', 'Branded'),
('amp / indented / organic', 'Indented Results', 'Branded'),
('amp / indented / ratings / organic', 'Indented Results', 'Branded'),
('amp / interesting finds', 'Interesting Finds', 'Research'),
('interesting finds', 'Interesting Finds', 'Research'),
('carousel / knowledge graph / other', 'Knowledge Graph', 'Split/Fractured'),
('carousel / knowledge graph / videos', 'Knowledge Graph', 'Split/Fractured'),
('knowledge graph / other', 'Knowledge Graph', 'Branded'),
('knowledge graph / related searches', 'Knowledge Graph', 'Split/Fractured'),
('ad / placesv3', 'Local Pack', 'Local'),
('ad / placesv3 / ratings', 'Local Pack', 'Local'),
('placesv3', 'Local Pack', 'Local'),
('amp / carousel / news', 'News', 'Fresh/News'),
('amp / news', 'News', 'Fresh/News'),
('carousel / news', 'News', 'Fresh/News'),
('news', 'News', 'Fresh/News'),
('people also ask', 'People Also Ask', 'Research'),
('carousel / podcasts', 'Podcasts', 'Split/Fractured'),
('popular products', 'Popular Products', 'Research'),
('carousel / q&a', 'Q&A', 'Answer'),
('amp / image / ratings / organic', 'Ratings', 'Research'),
('amp / ratings / organic', 'Ratings', 'Research'),
('faq / ratings / organic', 'Ratings', 'Research'),
('image / ratings / organic', 'Ratings', 'Research'),
('placesv3 / ratings', 'Ratings', 'Local'),
('ratings / organic', 'Ratings', 'Research'),
('carousel / image / ratings / organic', 'Ratings', 'Research'),
('ratings / recipes', 'Recipes', 'Research'),
('carousel / ratings / recipes', 'Recipes', 'Research'),
('carousel / recipes', 'Recipes', 'Research'),
('recipes', 'Recipes', 'Research'),
('refine by', 'Refine By', 'Research'),
('related searches', 'Related Searches', 'Research'),
('carousel / research', 'Research Carousel', 'Research'),
('carousel / shopping', 'Shopping Carousel', 'Transactional'),
('organic / sitelinks', 'Sitelinks', 'Transactional'),
('twitter box', 'Twitter', 'Twitter Carousel'),
('carousel / videos', 'Videos', 'Video'),
('videos', 'Videos', 'Video'),
('amp / organic / web stories', 'Web Stories', 'Fresh/News'),
('carousel / placesv3 / ratings', 'Ratings', 'Local'),
('price / organic', 'Product', 'Visual'),
('price / ratings / organic', 'Product', 'Visual'),
('carousel / organic', 'Carousel', 'Visual'),
('faq / image / organic', 'FAQs', 'Visual'),
('faq / price / ratings / organic', 'Product', 'Visual'),
('faq / image / price / ratings / organic', 'Product', 'Visual'),
('ratings / organic / sitelinks', 'Sitelinks', 'Visual'),
('indented / price / organic', 'Indented Results', 'Visual'),
('faq / image / ratings / organic', 'FAQs', 'Visual'),
('price / ratings / organic / sitelinks', 'Sitelinks', 'Visual'),
('amp / organic / sitelinks', 'Sitelinks', 'Visual'),
('indented / price / ratings / organic', 'Indented Results', 'Visual'),
('amp / ratings / organic / sitelinks', 'Sitelinks', 'Visual'),
('carousel / knowledge graph / other / ratings', 'Carousel', 'Visual');